sudo: required
services:
  - docker

before_install:
  - docker build -t viscarra97/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true viscarra97/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-207101409492"
  bucket_path: "react-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
